export const firstName = 'Kush';
export const lastName = 'Patel';
export const name = `${firstName} ${lastName}`;
export const githubUsername = 'zettachad';
export const githubURL = `https://github.com/${githubUsername}`;
export const discordID = '788684047894839307';
export const discordURL = `https://discordapp.com/users/${discordID}`;
export const twtxt = 'https://twtxt.kush.in/'
export const website = 'https://www.kush.in/';
export const bio = `I'm ${name}, a developer from India. I'm building guided missile systems using turbo encabulators. This website is big div energy`;
export const dob = '2006-04-05';
